# Generated by Django 6.0.3 on 2026-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(help_text="Insira o nome", max_length=100)),
                ("idade", models.IntegerField(help_text="Insira a idade")),
                (
                    "email",
                    models.EmailField(help_text="Informe o email", max_length=255),
                ),
                (
                    "telefone",
                    models.CharField(help_text="Telefone com DDD e DDI", max_length=20),
                ),
                (
                    "dtNascimento",
                    models.DateField(
                        help_text="Nascimento no formato DD/MM/AAAA",
                        verbose_name="Data de nascimento",
                    ),
                ),
            ],
        ),
    ]
